### PR TITLE
update links to spreadsheets

### PR DESCRIPTION
**Pull request by jananiravi**
https://github.com/jennybc/here_here

This makes transitions across users/systems easy and is much more robust than `setwd`. This is one of those things I wish I knew from day 1 so that I didn't have to rewrite all my old codes! :)

### CODE REVIEW

**Comment by jananiravi** [comment]
I just noticed this discussion here @ErinBecker & @naupaka 😆 
https://github.com/datacarpentry/genomics-r-intro/issues/15 👍

**Comment by jananiravi** [comment]
@ErinBecker would we be including the `here` package (`here::here`)? If not, I can close the PR.

**Comment by jananiravi** [comment]
@fmichonneau in addition to the `here` package mentioned above, I have updated the cheatsheet URLs of both `dplyr` and `rmarkdown` referenced here: https://github.com/datacarpentry/genomics-r-intro/issues/52

**Comment by fmichonneau** [comment]
@jananiravi would it be OK if I "hijack" your pull request to only update the cheatsheets for now?

I think `here` is very useful, but I worry that it solves a  problem that beginners don't know they have, and therefore it might make them more confused. Maybe we can create a callout box about how to manage paths in their scripts?

**Comment by jananiravi** [comment]
Sure, @fmichonneau, sounds good. Go ahead and use the cheatsheets for now.
I do agree that `here` may be an additional concept that newbies would have to pick up in addition to all others. Then again, it's only one function in that package, for all practical purposes. So, introducing `Rproj` + `here` as early as possible at the time of onboarding might be very helpful in the long run is what I thought. Yes, I agree, callout box is a good first step until we resolve this. thanks!

**Comment by fmichonneau** [comment]
Thanks, would you be willing to write up a call out box about using `here` and managing paths in general in scripts?

**Pull request merged**
