### PR TITLE
Add *.Rproj to .gitignore

### PR DESCRIPTION
**Pull request by ahmedmoustafa**
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._

_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._

_If any relevant discussions have taken place elsewhere, please provide links to these._

<details>

For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

</details>

### CODE REVIEW

**Comment by zkamvar** [comment]
I would actually recommend _not_ adding the `*.Rproj` file to the gitignore. Instead, I would recommend to add an R Project file to the root.

**Comment by zkamvar** [comment]
I would suggest to close this in favour of #239

**Comment by ahmedmoustafa** [comment]
I just think ignoring the rstudio project will avoid system (or local)-specific settings

**Comment by zkamvar** [comment]
> I just think ignoring the rstudio project will avoid system (or local)-specific settings

Can you explain what you mean by this? system/local specific settings generated by RStudio are stored in a `.Rproj.user/` directory, which is ignored by default: https://github.com/datacarpentry/genomics-r-intro/blob/e7b767b19ba62fc4587cfa24d5c72c0bb62d50ad/.gitignore#L19-L20

If anything, the RStudio project file will help avoid system/local specific settings because it standardises how RStudio users interact with the project (e.g. it never saves the workspace) and it doesn't affect how other users interact (I know because I use neovim).

**Comment by ahmedmoustafa** [comment]
It is just that when I cloned the repo as a project from within rstudio, rstudio created `genomics-r-intro.Rproj`, so I thought it'd better to git ignore the project file.

**Comment by zkamvar** [comment]
> It is just that when I cloned the repo as a project from within rstudio, rstudio created `genomics-r-intro.Rproj`, so I thought it'd better to git ignore the project file.

Again, #239 adds that file in here so that you won't have to worry about that surprise. Not including the Rproj file during the transition was a mistake of mine. For context, the lesson template contains an Rproj file: https://github.com/carpentries/workbench-template-md

**Comment by ahmedmoustafa** [comment]
Got it. Thank you!

**Pull request closed without merging**
