### PR TITLE
clean up dplyr lesson + add challenges

### PR DESCRIPTION
**Pull request by fmichonneau**
this PR introduces the changes I made when teaching this lesson at U of Arizona on May 31.

(I had accidentally pushed this directly to master but reverted the change)

### CODE REVIEW

**Comment by tobyhodges** [comment]
I was going to submit a separate PR for this but, as you have this one already open, François, perhaps you could also push a fix to close the parentheses in the link to https://cran.r-project.org/package=dplyr (line 36) of `04-dplyr.Rmd `?

**Comment by tobyhodges** [comment]
BTW it looks like the rendered pages already include your changes https://datacarpentry.org/genomics-r-intro/04-dplyr/index.html

**Comment by tobyhodges** [comment]
Two more fixes you could add, while you're at it... 🙂

1. as mentioned in #61, it would be best to remove the uses of the word "dataframe" from this episode.
2. you fixed the problem with piping to `head()` in the `mutate` example, but the text above still syas "We’ll show only the first six rows of data."

**Comment by NadineBestard** [comment]
I spotted the old issue #29 It is also an easy change on the dplyr lesson (replace "cover 6 of the most commonly used" by "cover 5 of the most commonly used" on _episodes_rmd/04-dplyr.Rmd line 42 ). If you wish I could open a new PR for that, but seen #61 was added here, I guess this PR could also adress #29

**Pull request closed without merging**
