### PR TITLE
removing knitr lesson per issue #142

### PR DESCRIPTION
**Pull request by ytakemon**
@naupaka, here's the pull request for removing Knitr, as we discussed this morning. Hopefully, this doesn't break anything!

### CODE REVIEW

**Comment by ytakemon** [comment]
@zkamvar I'm not very familiar with this new infrastructure. Can you help me understand what is causing this build error? 
I just deleted an entire episode in the request.

**Comment by ytakemon** [comment]
I see. Thanks @zkamvar! All seems to be happy and green now.

**Comment by zkamvar** [comment]
Yay! I'm glad that worked.

There was supposed to be an updated comment for this PR, but GitHub is on the struggle bus right now: https://www.githubstatus.com/incidents/pr3498h3qkfy and this PR is pretty straightforward.

**Comment by naupaka** [comment]
Thanks @ytakemon !

**Pull request merged**
